#Application Url
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser Configuration
browser = chrome

#Credentials
username = admin
password = admin123

#Implicit Wait in seconds
#implicitWait = 10

headless = true


